package:  kal_termine
version:  '3.4.4'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:kal_termine'
    perm:  kal_termine[]
    icon:  rex-icon fa-calendar
    subpages:
        introduction:    { title: 'translate:introduction' }
        description:     { title: 'translate:description' }
        details:         { title: 'translate:details' }
        table_structure: { title: 'translate:table_structure' }
        example:         { title: 'translate:example' }
        settings:        { title: 'translate:settings' }

requires:
    redaxo: ^5.3.0
