package:  kal_termine
version:  '3.7'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:kal_termine'
    perm:  kal_termine[]
    icon:  rex-icon fa-calendar-days
    subpages:
        introduction:      { title: 'translate:introduction' }
        description:       { title: 'translate:description' }
        details:           { title: 'translate:details' }
        table:             { title: 'translate:table' }
        example:           { title: 'translate:example' }
        settings:          { title: 'translate:settings' }
        settings_termlist: { title: 'translate:settings_termlist' }

requires:
    redaxo: ^5.3.0
